### ISSUE TITLE
Incorrect translation for 2MB pages

### ISSUE THREAD

**Issue by hypervisor** [can1357/physical_mem_controller#1]
https://github.com/can1357/physical_mem_controller/blob/master/MemoryController.h#L267

If PDE maps a 2MB page you use PFN_TO_PAGE macro, which bitshifts to the left by 12 bits, you should use 21 instead

**Comment by can1357** [comment]
Referring to the Table 4-17 in `Intel® 64 and IA-32 Architectures Software Developer’s Manual: Volume 3` you can see that a PDE that maps a 2-MB page looks like this:
```
20:13 Reserved (must be 0)
(M–1):21 Physical address of the 2-MByte page referenced by this entry
```

Now going back to the source code, if you check the PDE decleration at https://github.com/can1357/physical_mem_controller/blob/master/MemoryController.h#L101, you can see that its assigned 40 bits, this is because since bottom bits are guaranteed to be 0, this makes that value shifted by default, so this is perfectly valid.

**Comment by hypervisor** [comment]
I see, thanks for the explanation
